---

- name: "Get ec2 facts"
  action: ec2_facts

- name: "Update Package Lists"
  apt: 
    update_cache: yes

- name: "Install AWS CloudWatch Logs Agent"
  shell: python /tmp/awslogs-agent-setup.py -n -r {{ ansible_ec2_placement_region }} -c /etc/awslogs/awslogs.conf

